# Generated by Django 6.0.5 on 2026-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_canje', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
