# Generated by Django 6.0.5 on 2026-05-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0002_recuerdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuerdo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recuerdos/'),
        ),
    ]
