# Generated by Django 6.0.5 on 2026-05-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0003_recuerdo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuerdo',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
